### ISSUE TITLE
No module named “winsound”

### ISSUE THREAD

**Issue by maanya125** [berkaymizrak/Proxy-Scraper-Checker#6]
How to fix this?

**Comment by berkaymizrak** [comment]
Hi, 
`pip install winsound`
must fix the problem. However this is only for Windows operation system. If you are using except of Windows then you can simply delete the lines importing winsound and the ones that using winsound.

**Comment by berkaymizrak** [comment]
Sure I will make an update today

**Comment by berkaymizrak** [comment]
You can now pull it. "Progress.py" is updated under "Functions" folder. You can see the change that I just don't import winsound and don't use winsound if os is not Windows.

**Comment by maanya125** [comment]
Ok

**Comment by maanya125** [comment]
Bro still error comes

**Comment by maanya125** [comment]
![Uploading F13B5DC9-43C9-484B-B49B-F321B5B5B807.jpeg…]()

**Comment by maanya125** [comment]
![968D7AB6-E0A0-451F-8C46-0C1A4FB959DE](https://user-images.githubusercontent.com/83495427/132800143-a3d5b85d-26de-4631-af79-f506dad5b21d.jpeg)

**Comment by berkaymizrak** [comment]
The problem is fixed. as you see, it is just promting a message that sound does not work and continues to work. You should check each line of code and modify for your use of purpose. The problem you are seeing is at check_run function. This is developed for allowing or not allowing program to run with connecting any API of yours. If you have an API that can tell the program run or not run, you can use that, otherwise you can remove the check_run line.

![image](https://user-images.githubusercontent.com/36295121/132953763-deccab0b-6996-44d4-b1ee-8a0806c8a54d.png)

**Comment by maanya125** [comment]
Ok
